name: Run Torch Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Core Unit Tests
      run: docker build -t rust-onnx-runtime . && docker run --rm rust-onnx-runtime -p surrealml-core --features torch-tests
